repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.10
        args: [--profile, black]
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  #       language_version: python3.10
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.0.0
  #   hooks:
  #     - id: mypy
  #       language_version: python3.10
  #       args: [--ignore-missing-imports]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.2
    hooks:
      - id: pylint
        language_version: python3.10
        entry: python custom_pylint_plugin.py
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.3
    hooks:
      - id: bandit
        language_version: python3.10
        args: [-r]
